#!/bin/bash
#SBATCH -n 1
#SBATCH -p gpu
#SBATCH -t 05:30:00
#SBATCH -o siam.output
#SBATCH -e siam.error

module load python/2.7.11
module load cuda/7.5.18
module load cudnn/7.5-v5

python train_model.py --train_model 'siamese' \
                      --margin 1 \
                      --faction_same 0.2\
                      --summary 1\
                      --saver 1\
                      --max_steps 50000\
                      --logdir ./logs/cifar10/siamese/step50k_new


