#!/bin/bash
#SBATCH -n 1
#SBATCH -p gpu
#SBATCH -t 02:00:00
#SBATCH -o siam.output
#SBATCH -e siam.error

module load python/2.7.11
module load cuda/7.5.18
module load cudnn/7.5-v5

python train_model.py --train_model 'siamese' \
                      --margin 1 \
                      --faction_same 0.3\
                      --reg_strength 0.001 \
                      --dropout_rate 0.5 \
                      --eval_freq 3000


