#!/bin/bash
#SBATCH -n 1
#SBATCH -p gpu
#SBATCH -t 01:00:00
#SBATCH -o train.output
#SBATCH -e train.error

module load python/2.7.11
module load cuda/7.5.18
module load cudnn/7.5-v5


python train_model.py --reg_strength 0.0001 \
                      --dropout_rate 0.5 \
                      --batch_normal 0\
                      --summary 0\
                      --saver 1\

python train_model.py --is_train 0

python svm_classifier.py
